### ISSUE TITLE
VexRiscv Core Generating Configuration

### ISSUE THREAD

**Issue by B10615053** [smunaut/iCE40linux#1]
Hello, I am recently researching for minimum requirement of RISC-V for Embedded Linux, and I am really interested in your project.
I would like to build the VexRiscv Core that you mentioned in this repository, but I only found [VexRiscv.v](https://github.com/smunaut/iCE40linux/blob/master/gateware/riscv_linux/rtl/VexRiscv.v) in this repository. I also found another project named [VexRiscv-no2soc](https://github.com/smunaut/VexRiscv-no2soc) in your github, but the configuration of `VexRiscv-no2soc` is "small" which will not generate MMU like `VexRiscv.v` does.
```scala
case class ArgConfig(
  debug : Boolean = false,
  iCacheSize : Int = 1024,
  dCacheSize : Int = 0,
  mulDiv : Boolean = false,
  singleCycleMulDiv : Boolean = false,
  singleCycleShift : Boolean = true,
  relaxedPcCalculation : Boolean = false,
  bypass : Boolean = true,
  externalInterruptArray : Boolean = true,
  resetVector : BigInt = null,
  machineTrapVector : BigInt = null,
  prediction : BranchPrediction = STATIC,
  outputFile : String = "VexRiscv",
  csrPluginConfig : String = "small",
  dBusCachedRelaxedMemoryTranslationRegister : Boolean = false,
  dBusCachedEarlyWaysHits : Boolean = true
)
```
I would like to ask what VexRiscv Core Generating Configuration do you use in this repository?

**Comment by smunaut** [comment]
Just pushed a `ice40linux` branch on the https://github.com/smunaut/VexRiscv-no2soc repo which AFAIR is the config I used.
